models/Serial.php
<?php

namespace app\models;

use yii\db\ActiveRecord;

/**
 * @property integer id
 * @property string name
 * @property string description
 * @property string image
 * @property integer year
 * @property string status_id
 * @property string studio_id
 */
class Serial extends ActiveRecord
{
    public static function tableName()
    {
        return '{{%serials}}';
    }

    public function getStatus()
    {
        return $this->hasOne('app\models\Status', ['id' => 'status_id']);
    }

    public function getStudio()
    {
        return $this->hasOne('app\models\Studio', ['id' => 'studio_id']);
    }

    public function getLastSeries()
    {
        return $this->hasOne('app\models\Season', ['serial_id' => 'id'])->orderBy(['season_num' => SORT_DESC])->joinWith('lastSeries');
    }

    public function getGenres()
    {
        return $this->hasMany('app\models\SerialGenre', ['serial_id' => 'id'])->joinWith('genre');
    }

    public function getCountries()
    {
        return $this->hasMany('app\models\SerialCountry', ['serial_id' => 'id'])->joinWith('country');
    }

    public function getProducer()
    {
        return $this->hasOne('app\models\Season', ['serial_id' => 'id'])->with('lastSeries')->with('producer');
    }
}

controllers/SerialController.php
<?php

namespace app\controllers;

use app\models\Country;
use app\models\form\AddSerialForm;
use app\models\Genres;
use app\models\People;
use app\models\Role;
use app\models\Season;
use app\models\Serial;
use app\models\SerialGenre;
use app\models\Series;
use app\models\SeriesPeople;
use app\models\Status;
use app\models\Studio;
use app\models\Tag;
use app\models\TagSerial;
use Yii;
use yii\web\Controller;
use yii\web\UploadedFile;

class SerialController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => 'yii\filters\AccessControl',
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => 'yii\filters\VerbFilter',
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionAdd()
    {
        if (Yii::$app->user->isGuest && Yii::$app->user->identity->is_admin == 1) {
            return $this->goHome();
        }

        $model = new AddSerialForm();

        if ($model->load(Yii::$app->request->post())) {
            $model->image = UploadedFile::getInstance($model, 'image');

            $fileName = '/images/' . $model->image->baseName . '.' . $model->image->extension;
            $model->image->saveAs(Yii::$app->basePath . '/web' . $fileName);

            $serial = new Serial();
            $serial->name = $model->name;
            $serial->description = $model->description;
            $serial->year = 2020 - $model->year;
            $serial->status_id = $model->status_id;
            $serial->studio_id = $model->studio_id;
            $serial->image = $fileName;
            $serial->save();

            foreach ($model->genres as $genre) {
                $serialGenre = new SerialGenre();
                $serialGenre->genre_id = $genre;
                $serialGenre->serial_id = $serial->id;
                $serialGenre->save();
            }

            foreach ($model->tags as $tag) {
                $serialGenre = new TagSerial();
                $serialGenre->tag_id = $tag;
                $serialGenre->serial_id = $serial->id;
                $serialGenre->save();
            }
        }

        $genres = [];
        foreach (Genres::find()->all() as $item) {
            $genres[$item['id']] = $item['name'];
        }

        $tags = [];
        foreach (Tag::find()->all() as $item) {
            $tags[$item['id']] = $item['name'];
        }

        $countries = [];
        foreach (Country::find()->all() as $item) {
            $countries[$item['id']] = $item['name'];
        }

        $statuses = [];
        foreach (Status::find()->all() as $item) {
            $statuses[$item['id']] = $item['name'];
        }

        $studios = [];
        foreach (Studio::find()->all() as $item) {
            $studios[$item['id']] = $item['name'];
        }

        $data = [
            'model' => $model,
            'genres' => $genres,
            'tags' => $tags,
            'countries' => $countries,
            'years' => range(2020, 1900, -1),
            'statuses' => $statuses,
            'studios' => $studios,
        ];

        return $this->render('add', $data);
    }

    public function actionIndex($id, $season_id = null)
    {
        $serial = Serial::find()->where(['id' => $id])->with(['genres', 'status', 'countries'])->asArray()->one();

        $producers = People::find()->select([People::tableName() . '.*', SeriesPeople::tableName() . '.*'])
            ->join('LEFT JOIN', SeriesPeople::tableName(), SeriesPeople::tableName() . '.people_id = ' . People::tableName() . '.id')
            ->join('LEFT JOIN', Series::tableName(), SeriesPeople::tableName() . '.series_id = ' . Series::tableName() . '.id')
            ->join('LEFT JOIN', Season::tableName(), Series::tableName() . '.season_id = ' . Season::tableName() . '.id')
            ->join('LEFT JOIN', Serial::tableName(), Season::tableName() . '.serial_id = ' . Serial::tableName() . '.id')
            ->where(['=', Serial::tableName() . '.id', $id])->asArray()->all();

        foreach ($producers as &$item) {
            $item['role'] = Role::findOne(['id' => $item['role_id']])->name;
        }

        $serial['producers'] = $producers;
        $serial['seasons'] = Season::find()->joinWith('series')->where(['=', 'serial_id', $id])->asArray()->all();

        if ($season_id == null) {
            $season_id = 0;
            $serial['seasonSelected'] = $serial['seasons'][0];
        } else {
            $serial['seasonSelected'] = Season::find()->where(['=', 'id', $season_id])->with('series')->asArray()->one();
        }


        return $this->render('serial', ['serial' => $serial, 'season_id' => $season_id]);
    }
}

views/serial/add.php
<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

$this->title = 'Добавить сериал';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="row">
    <?php $form = ActiveForm::begin(); ?>
    <?= $form->field($model, 'name')->label('Название') ?>
    <?= $form->field($model, 'genres')->checkboxList($genres)->label('Жанры') ?>
    <?= $form->field($model, 'tags')->checkboxList($tags)->label('Теги') ?>
    <?= $form->field($model, 'year')->dropDownList($years)->label('Год') ?>
    <?= $form->field($model, 'country_id')->dropDownList($countries)->label('Страна') ?>
    <?= $form->field($model, 'status_id')->dropDownList($statuses)->label('Статусы') ?>
    <?= $form->field($model, 'studio_id')->dropDownList($studios)->label('Студия') ?>
    <?= $form->field($model, 'description')->textarea()->label('Описание') ?>
    <?= $form->field($model, 'image')->fileInput()->label('Картинка') ?>
    <div class="row">
        <?= Html::submitButton('Добавить', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

views/serial/serial.php
<?php
use yii\helpers\Url;

?>
<div class="row">
    <div class="col-md-3">
        <img style="max-width: 300px;" src="<?= $serial['image']?>">
        <input type="hidden" name="id" value="<?= $serial['id']?>">
        <?php if (!Yii::$app->user->isGuest): ?>
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <a href="<?= Url::toRoute(['favorite/add', 'id' => $serial['id']]) ?>">В избранное</a>
            </div>
            <div class="col-md-2"></div>
        <?php endif ?>
    </div>
    <div class="col-md-5">
        <h3><?= $serial['name']?></h3>
        <div>
            Жанры:
            <?php foreach ($serial['genres'] as $genre): ?>
                <span><?= $genre['genre']['name'] ?> </span>
            <?php endforeach ?>
        </div>
        <p>Год выпуска: <span><?= $serial['year']?></span></p>
        <p>
            Роли:
            <?php foreach ($serial['producers'] as $producer): ?>
                <p><?= $producer['FIO'] ?> - <?= $producer['role'] ?> </p>
            <?php endforeach ?>
        </p>
        <p>Описание: <span><?= $serial['description']?></span></p>
        <div class="spacer"></div>
        <p>Сезон:
            <?php foreach ($serial['seasons'] as $season): ?>
                <a href="<?= Url::toRoute(['serial/index', 'id' => $serial['id'], 'season_id' => $season['id']])  ?>"><?= $season['season_num'] ?></a>
            <?php endforeach ?>
        </p>
        <?php foreach ($serial['seasonSelected']['series'] as $series): ?>
        <div class="row">
            <div class="col-md-4">
                <p>Номер серии</p>
                <p><?= $series['series'] ?></p>
            </div>
            <div class="col-md-4">
                <p>Название серии</p>
                <p><?= $series['name'] ?></p>
            </div>
            <div class="col-md-4">
                <p>Дата выхода</p>
                <p><?= $series['release_date'] ?></p>
            </div>
        </div>

        <?php endforeach ?>
    </div>
    <div class="col-md-4">
        <p>Дополнительная информация:</p>
        <p>Статус:<span><?= $serial['status']['name'] ?></span></p>
        <p>Страна производства:
            <?php foreach ($serial['countries'] as $country): ?>
                <span><?= $country['country']['name'] ?> </span>
            <?php endforeach ?>
        </p>
    </div>
</div>