controllers/GenreController.php
<?php

namespace app\controllers;

use app\models\form\AddGenreModel;
use app\models\Genres;
use Yii;
use yii\web\Controller;

class GenreController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => 'yii\filters\AccessControl',
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => 'yii\filters\VerbFilter',
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionAdd()
    {
        if (Yii::$app->user->isGuest && Yii::$app->user->identity->is_admin == 1) {
            return $this->goHome();
        }

        $model = new AddGenreModel();

        if ($model->load(Yii::$app->request->post())) {
            $genre = new Genres();
            $genre->name = $model->name;
            $genre->save();
        }

        $data = [
            'model' => $model,
        ];

        return $this->render('add', $data);
    }
}

controllers/PeopleController.php
<?php

namespace app\controllers;

use app\models\form\AddPeopleForm;
use app\models\People;
use Yii;
use yii\helpers\Url;
use yii\web\Controller;

class PeopleController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => 'yii\filters\AccessControl',
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => 'yii\filters\VerbFilter',
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionAdd()
    {
        if (Yii::$app->user->isGuest && Yii::$app->user->identity->is_admin == 1) {
            return $this->goHome();
        }

        $model = new AddPeopleForm();

        if ($model->load(Yii::$app->request->post())) {
            $people = new People();
            $people->FIO = $model->FIO;
            $people->date_birth = $model->date_birth;
            $people->biography = $model->biography;
            $people->save();

            $this->redirect(Url::toRoute(['site/adds']));
        }

        $data = [
            'model' => $model,
        ];

        return $this->render('add', $data);
    }
}

controllers/RoleController.php
<?php

namespace app\controllers;

use app\models\form\AddRoleModel;
use app\models\Role;
use Yii;
use yii\web\Controller;

class RoleController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => 'yii\filters\AccessControl',
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => 'yii\filters\VerbFilter',
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionAdd()
    {
        if (Yii::$app->user->isGuest && Yii::$app->user->identity->is_admin == 1) {
            return $this->goHome();
        }

        $model = new AddRoleModel();

        if ($model->load(Yii::$app->request->post())) {
            $role = new Role();
            $role->name = $model->name;
            $role->save();
        }

        $data = [
            'model' => $model,
        ];

        return $this->render('add', $data);
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Country;
use app\models\form\ContactForm;
use app\models\form\LoginForm;
use app\models\form\RegisterFrom;
use app\models\Genres;
use app\models\Season;
use app\models\Serial;
use app\models\Series;
use app\models\Status;
use app\models\Studio;
use app\models\Tag;
use Yii;
use yii\web\Controller;
use yii\web\Response;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => 'yii\filters\AccessControl',
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => 'yii\filters\VerbFilter',
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $request = Yii::$app->request;

        $genres = Genres::find()->all();
        $countries = Country::find()->all();
        $studios = Studio::find()->all();
        $statuses = Status::find()->all();
        $tags = Tag::find()->all();

        $series = Series::find()->join('LEFT JOIN', 'seasons', 'seasons.id = series.season_id');
        $series->join('LEFT JOIN', 'serials', 'serials.id = seasons.serial_id');

        if ($request->get('genre_id', 0) != 0) {
            $series->join('LEFT JOIN', 'serials_genres', 'serials_genres.serial_id = serials.id');
            $series->where(['=', 'serials_genres.genre_id', $request->get('genre_id')]);
        }

        if ($request->get('country_id', 0) != 0) {
            $series->join('LEFT JOIN', 'serials_countries', 'serials_countries.serial_id = serials.id');
            $series->where(['=', 'serials_countries.country_id', $request->get('country_id')]);
        }

        if ($request->get('year', 0) != 0) {
            $series->where(['=', 'YEAR(release_date)', $request->get('year')]);
        }

        if ($request->get('status_id', 0) != 0) {
            $series->where(['=', 'status_id', $request->get('status_id')]);
        }

        if ($request->get('studio_id', 0) != 0) {
            $series->where(['=', 'studio_id', $request->get('studio_id')]);
        }

        if ($request->get('tag_id', 0) != 0) {
            $series->join('LEFT JOIN', 'tag_serial', 'tag_serial.serial_id = serials.id');
            $series->where(['=', 'tag_serial.tag_id', $request->get('tag_id')]);
        }

        $series = $series->with('seasonSerial')->with('seasonSerialLast')->asArray()->all();

        foreach ($series as &$item) {
            $item['season'] = Season::find()->where(['=', 'id', $item['season_id']])->asArray()->one();
            $item['season']['serial'] = Serial::find()->where(['=', 'id', $item['season']['serial_id']])->asArray()->one();
        }

        $data = [
            'series' => $series,
            'genres' => $genres,
            'countries' => $countries,
            'studios' => $studios,
            'statuses' => $statuses,
            'years' => range(2020, 1900, -1),
            'tags' => $tags,
        ];

        return $this->render('index', $data);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';

        return $this->render('login', ['model' => $model,]);
    }

    public function actionRegister()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new RegisterFrom();
        if ($model->load(Yii::$app->request->post()) && $model->register()) {
            return $this->goHome();
        }

        return $this->render('register', ['model' => $model,]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }

        return $this->render('contact', ['model' => $model,]);
    }

    public function actionAdds()
    {
        return $this->render('adds');
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/adds.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Url;

$this->title = 'Добавление';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <div>
        <a href="<?= Url::toRoute(['/country/add']) ?>">Добавить Страну</a>
    </div>
    <div>
        <a href="<?= Url::toRoute(['/genre/add']) ?>">Добавить Жанр</a>
    </div>
    <div>
        <a href="<?= Url::toRoute(['/people/add']) ?>">Добавить Актера</a>
    </div>
    <div>
        <a href="<?= Url::toRoute(['/role/add']) ?>">Добавить Роль</a>
    </div>
    <div>
        <a href="<?= Url::toRoute(['/status/add']) ?>">Добавить Статус</a>
    </div>
    <div>
        <a href="<?= Url::toRoute(['/serial/add']) ?>">Добавить Сериал</a>
    </div>
    <div>
        <a href="<?= Url::toRoute(['/season/add']) ?>">Добавить Сезон</a>
    </div>
    <div>
        <a href="<?= Url::toRoute(['/series/serial']) ?>">Добавить Серию</a>
    </div>
    <div>
        <a href="<?= Url::toRoute(['/manager/index']) ?>">Добавить актера к серии</a>
    </div>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
use yii\helpers\Url;
use app\widgets\FilmItem\FilmItem;

$this->title = 'Сериалы';
?>

    <form method="GET">
        <div class="row">
            <div class="col-md-3">
                <p>Жанры</p>
                <select name="genre_id">
                    <option value="0">Любой</option>
                    <?php foreach ($genres as $genre): ?>
                        <option value="<?= $genre['id'] ?>"><?= $genre['name'] ?></option>
                    <?php endforeach ?>
                </select>
            </div>
            <div class="col-md-3">
                <p>Страна производителя</p>
                <select name="country_id">
                    <option value="0">Любая</option>
                    <?php foreach ($countries as $county): ?>
                        <option value="<?= $county['id'] ?>"><?= $county['name'] ?></option>
                    <?php endforeach ?>
                </select>
            </div>
            <div class="col-md-3">
                <p>Год выхода</p>
                <select name="year">
                    <option value="0">Любая</option>
                    <?php foreach ($years as $year): ?>
                        <option value="<?= $year ?>"><?= $year ?></option>
                    <?php endforeach ?>
                </select>
            </div>
            <div class="col-md-3">
                <p>Статусы</p>
                <select name="status_id">
                    <option value="0">Любая</option>
                    <?php foreach ($statuses as $status): ?>
                        <option value="<?= $status['id'] ?>"><?= $status['name'] ?></option>
                    <?php endforeach ?>
                </select>
            </div>
            <div class="col-md-3">
                <p>Студия</p>
                <select name="studio_id">
                    <option value="0">Любая</option>
                    <?php foreach ($studios as $studio): ?>
                        <option value="<?= $studio['id'] ?>"><?= $studio['name'] ?></option>
                    <?php endforeach ?>
                </select>
            </div>
            <div class="col-md-3">
                <p>Теги</p>
                <select name="tag_id">
                    <option value="0">Любая</option>
                    <?php foreach ($tags as $tag): ?>
                        <option value="<?= $tag['id'] ?>"><?= $tag['name'] ?></option>
                    <?php endforeach ?>
                </select>
            </div>
            <div class="col-md-3"></div>
            <div class="col-md-3"></div>
            <div class="col-md-3"></div>
            <div class="col-md-3"></div>
            <div class="col-md-3">
                <input type="submit" value="Найти">
            </div>
        </div>

    </form>

<div class="row">
    <h1>
        Новые серии
    </h1>
</div>
<?php
$items = [];

foreach ($series as $item) {
    $items[] = [
        'imgSrc' => $item['season']['serial']['image'],
        'text' => $item['name'],
        'name' => $item['season']['serial']['name'],
        'description' => $item['description'],
        'hrefSrc' => Url::toRoute(['serial/index', 'id' => $item['season']['serial']['id']]),
        'lastSeason' => $item['season']['season_num'],
        'lastSeries' => $item['series'],
    ];
}

?>
<div class="row">
    <?php foreach ($items as $item): ?>
        <div class="col-md-4">
            <?= FilmItem::widget(['options' => $item]) ?>
        </div>
    <?php endforeach ?>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/site/register.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Register';
$this->params['breadcrumbs'][] = $this->title;
?>

<div>
    <h1><?= $this->title ?></h1>
    <?php $form = ActiveForm::begin(); ?>
    <?= $form->field($model, 'username') ?>
    <?= $form->field($model, 'password')->passwordInput() ?>
    <div class="row">
        <?= Html::submitButton('Register', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
    </div>
    <?php ActiveForm::end(); ?>

</div>